apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          env:
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "http"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_INSTANCE_OWNER_MANAGED_BY_ENV
              value: "true"
            - name: N8N_INSTANCE_OWNER_EMAIL
              value: "admin@dataharbor.local"
            - name: N8N_INSTANCE_OWNER_PASSWORD_HASH
              value: "$2a$10$xTXrj1FtAz8bpHA8/OSA..91FlQixTy7xZfIm4nx5PLSfFTVKktm6"
            - name: N8N_INSTANCE_OWNER_FIRST_NAME
              value: "Admin"
            - name: N8N_INSTANCE_OWNER_LAST_NAME
              value: "User"
            - name: GENERIC_TIMEZONE
              value: "UTC"
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
