"""Build Dagster workspace.yaml with one code location per bundle (+ core)."""
from __future__ import annotations

import logging
import os
from typing import Any

import yaml

from bundles.plugin_contract import (
    BundleContractError,
    iter_bundle_dirs,
    load_manifest,
    resolve_dagster_entrypoint,
)
from bundles.validator import BundleValidator

logger = logging.getLogger(__name__)

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_WORKSPACE_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "workspace.yaml"
)
BUNDLES_DIR = os.path.join(PROJECT_ROOT, "bundles")


def _core_location(working_directory: str) -> dict[str, Any]:
    return {
        "python_module": {
            "module_name": "apps.dagster_app.definitions",
            "attribute": "defs",
            "location_name": "core",
            "working_directory": working_directory,
        }
    }


def _bundle_location(
    bundle_name: str,
    module_leaf: str,
    attr: str,
    working_directory: str,
) -> dict[str, Any]:
    return {
        "python_module": {
            "module_name": f"bundles.{bundle_name}.{module_leaf}",
            "attribute": attr,
            "location_name": f"bundle_{bundle_name}",
            "working_directory": working_directory,
        }
    }


def discover_workspace_locations(
    *,
    bundles_dir: str | None = None,
    project_root: str | None = None,
    skip_invalid: bool = True,
) -> tuple[list[dict[str, Any]], list[str]]:
    """
    Return (load_from entries, warnings).

    Invalid / non-Dagster bundles are skipped by default so a broken plugin
    does not block workspace generation (Dagster then isolates per location).
    """
    root = os.path.abspath(project_root or PROJECT_ROOT)
    bundles_root = bundles_dir or os.path.join(root, "bundles")
    load_from: list[dict[str, Any]] = [_core_location(root)]
    warnings: list[str] = []

    for name, path in iter_bundle_dirs(bundles_root):
        is_valid, errors = BundleValidator(path).validate()
        if not is_valid:
            msg = f"skip bundle '{name}' (invalid): " + "; ".join(errors)
            if skip_invalid:
                warnings.append(msg)
                logger.warning(msg)
                continue
            raise BundleContractError(msg)

        try:
            manifest = load_manifest(path)
        except Exception as e:
            warnings.append(f"skip bundle '{name}' (manifest): {e}")
            continue

        entrypoints = manifest.get("entrypoints") or {}
        if isinstance(entrypoints, dict) and entrypoints.get("dagster") is None:
            warnings.append(f"skip bundle '{name}' (entrypoints.dagster=null)")
            continue

        try:
            module_leaf, attr = resolve_dagster_entrypoint(manifest)
        except BundleContractError as e:
            warnings.append(f"skip bundle '{name}' (entrypoint): {e}")
            continue

        module_file = os.path.join(path, f"{module_leaf}.py")
        if not os.path.exists(module_file):
            warnings.append(
                f"skip bundle '{name}' (missing {module_leaf}.py for Dagster entrypoint)"
            )
            continue

        load_from.append(_bundle_location(name, module_leaf, attr, root))
        logger.info(
            "Workspace location bundle_%s → bundles.%s.%s:%s",
            name,
            name,
            module_leaf,
            attr,
        )

    return load_from, warnings


def build_workspace_document(
    *,
    bundles_dir: str | None = None,
    project_root: str | None = None,
    skip_invalid: bool = True,
) -> tuple[dict[str, Any], list[str]]:
    load_from, warnings = discover_workspace_locations(
        bundles_dir=bundles_dir,
        project_root=project_root,
        skip_invalid=skip_invalid,
    )
    return {"load_from": load_from}, warnings


def write_workspace_yaml(
    path: str | None = None,
    *,
    bundles_dir: str | None = None,
    project_root: str | None = None,
    skip_invalid: bool = True,
) -> tuple[str, dict[str, Any], list[str]]:
    """Write workspace.yaml and return (path, document, warnings)."""
    out = os.path.abspath(path or DEFAULT_WORKSPACE_PATH)
    doc, warnings = build_workspace_document(
        bundles_dir=bundles_dir,
        project_root=project_root,
        skip_invalid=skip_invalid,
    )
    os.makedirs(os.path.dirname(out), exist_ok=True)
    header = (
        "# Auto-generated by DataHarbor (apps.dagster_app.workspace_builder).\n"
        "# One Dagster code location per bundle (+ core). Do not edit by hand;\n"
        "# run: harbor workspace refresh\n"
    )
    with open(out, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False)
    return out, doc, warnings


def location_names(doc: dict[str, Any]) -> list[str]:
    names: list[str] = []
    for entry in doc.get("load_from") or []:
        for key in ("python_module", "python_file", "grpc_server"):
            block = entry.get(key)
            if isinstance(block, dict) and block.get("location_name"):
                names.append(str(block["location_name"]))
    return names
