apiVersion: 1

deleteDatasources:
  - name: DataHarbor-PostgreSQL
    orgId: 1

datasources:
  - name: DataHarbor-PostgreSQL
    uid: DataHarbor-PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: dataharbor
    secureJsonData:
      password: dataharbor
    jsonData:
      database: dataharbor
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: true
