apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "local"
  LOG_LEVEL: "INFO"
  S3_ENDPOINT_URL: "http://seaweedfs-service:8333"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  S3_BUCKET_NAME: "dataharbor-raw"
  S3_REGION: "us-east-1"
  DAGSTER_HOME: "/tmp/dagster_home"
  QDRANT_URL: "http://qdrant-service:6333"
  QDRANT_API_KEY: ""
  QDRANT_COLLECTION: "dataharbor"
  QDRANT_VECTOR_SIZE: "512"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "dataharbor"
  POSTGRES_USER: "dataharbor"
  POSTGRES_PASSWORD: "dataharbor"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "8123"
